# Generated by Django 3.0.8 on 2020-07-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200720_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='labels',
            field=models.CharField(blank=True, choices=[('NA', 'New Arrivals'), ('BS', 'Best Sellers'), ('FA', 'Features')], max_length=50, null=True),
        ),
    ]
